// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxawknrbezyonkqtkvlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4YXdrbnJiZXp5b25rcXRrdmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjU5OTAsImV4cCI6MjA2NDMwMTk5MH0.-9JDSQNNlG6ladpEhPXqJYDddInWIBPg17s4H3fl4z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);